apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: predictApp
  template:
    metadata:
      labels:
        app: predictApp
    spec:
      containers:
      - name: predict-container
        image: imilabremodeling/ilatc:{{ .Values.deployment.image.tag }}
        command: ["/bin/sh"]
        args: ["-c", "while true; do python3 /home/jovyan/predict-code/inference.py;sleep 10;done"]
        ports: 
          - containerPort: 3000
        imagePullPolicy: Always

