apiVersion: apps/v1
kind: Deployment
metadata:
  name: predict-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictApp 
  template: 
    metadata:
      labels:
        app: predictApp
    spec:
      containers:
        - name: predict-container
          image: s410071012/node1_predict
          command: ["/bin/sh"]
          args: ["-c", "while true; do python3 /home/jovyan/predict-code/inference.py;sleep 10;done"]
          ports:
            - containerPort: 3000
          imagePullPolicy: Always        
     

